name: Manual RPM Build and Install Dispatch
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to RPM Build and Install From'
        required: true
      centos_ver:
        type: choice
        description: 'Centos Base image (options: 8/9) - Optional, default is 9'
        default: '9'
        options: 
          - '8'
          - '9'
      architecture:
        type: choice
        description: 'Architecture (options: linux/amd64 or linux/ppc64le) - Optional, default is linux/amd64'
        default: 'linux/amd64'
        options: 
          - 'linux/amd64'
          - 'linux/ppc64le'

jobs:
  build-rpm-and-install:
      runs-on: ubuntu-latest
      timeout-minutes: 90
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: ${{ inputs.branch }}
  
        - name: Run Non Containerized RPM Test
          run: |
            make rpm_build_and_install BUILD_S3SELECT=0 CENTOS_VER=${{ inputs.centos_ver }} CONTAINER_PLATFORM=${{ inputs.architecture }}
